spring:
  application:
    name: __ARTIFACT_ID__
  docker:
    compose:
      file: compose.yaml
  r2dbc:
    url: r2dbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:__ARTIFACT_ID__}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
  flyway:
    enabled: true
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:__ARTIFACT_ID__}
    user: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}

server:
  port: ${SERVER_PORT:__APP_PORT__}

management:
  server:
    port: ${MANAGEMENT_SERVER_PORT:__MANAGEMENT_PORT__}
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true
  tracing:
    enabled: ${MANAGEMENT_TRACING_ENABLED:true}
    sampling:
      probability: ${MANAGEMENT_TRACING_SAMPLING_PROBABILITY:0.1}

logging:
  level:
    __PACKAGE_NAME__: INFO
    org.springframework.web: INFO
