apiVersion: v1
kind: Service
metadata:
  name: {{ include "spring-service-starter.fullname" . }}
  labels:
    {{- include "spring-service-starter.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "spring-service-starter.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
    - name: management
      port: {{ .Values.management.port }}
      targetPort: management
